server:
  port: 8001
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://81.68.81.2:3306/mall?characterEncoding=utf-8&userSSL=false
    username: root
    password: Tbl2425209089yyds
  thymeleaf:
    cache: false
  rabbitmq:
    addresses: 81.68.81.2
    port: 5672
    username: guest
    password: Tbl2425209089yyds
  mvc:
    static-path-pattern: /pay/**
  resources:
    static-locations: classpath:/static/
pay:
  winxin-pay:
    app-id: wx3e6b9f1c5a7ff034
    merchant-id: 1614433647
    merchant-key: Aa111111111122222222223333333333

  ali-pay:
    app-id: 2021003123691047
    private-key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCVkKJpyO43Qge6YH7HXKogqPjSrezTuFA1nF1AzL8ep3Ria8mR+1wXkQ6bfQX0p9U0b2GhOVXkDTLfNtjPXYaUX63iEX5DwOpoNTElJO7/bedDnkYYDRUVEtenunlXWamcNhXMCfePNGBDgtYunz5jz/tpWakNKpeHpgor+UzFMWmUfy3w7aFLWzlbwxtC1fGU5Bps9mDm90L3jOBEXmS3UhxKE388SODVRkv24Lv+g+Q0dXY/8v0QoXpNs3LsT0U6qDCjYLneHVEpyqV8FxN/BIxdxKje0vQDpExpzZUlmbwz66TRIOIK0+o1NUcEOwnKae6f+ADmd6zinqYs2MvLAgMBAAECggEADkncCkkk4OiQ/nA7jGZA5o/d/ZqaFnv0Rbrjec5Vr+MFjmWHw0eFO8ci4x3llML37mN5q0Jj/z53jrWZru3bbo9ZeFB9hJGIk14JjOfjYUmpn18eiSuuyO2c5qw87WhmeML+ABkvqmGxlKGKPrf96OE0vpLPQK/B/DaToDHX8LqrTeOcS74PxxzDpmXqDNQdFQ2bEWQ8OiD66fpdTHNZy0DA6AKIT5aWjlMcxx6vD23I3xrJTALvupZRo/KhME8m5NNBAr0bitG3L4cILsGekQ5m5N+XWWeErQIuW4rvLWHDMtKXW5apWdtctk/EMMcygdbFB7DBAyZ2dw2cw9DCIQKBgQDPFNXORn6fa7tRv0g4e1QPI3ObRTkuG0qZGMI2EmJz+Gi3CM/X0XJ0vRf/JiSgdc6cx3bylj6ZW+o6vDY69aaSj1dAHWlL1HaZok9ugCx56OmX+59YNXQrr3nAEN3C9U5GEKnv6wXLpuVQmUKTFdpGyhWLv2sgKp7YgYzOPK1UGwKBgQC45YRnQanyVDcT2HCQUZRenP96KsCbk6Y+DNxwl3ETG5+WC0YtCNVFf+1oFASDTaGZfhlxb2OGB8xgzKShDFtJ38T8i3DQnysSP/WQSswqgb6MuJAv84vrbhhWjM/RMcTqhaRSOonv+az+CyTaGSwBJk2lI0nVaWW0YjYeXuoCEQKBgBAARCUUPWSEJo1CgooavXwN+TjeOHTflvwNdbRH52Oepji+bZD3lih/FAObJulfMP/cScyk32FqQMcZE/eqU5yvhsZlf2VknWVxrUGUlds1rBcaUk22k6tse7Pjmb8exVWUpAzt1BzQYJfBv+stnRgrNU7/E4AAyxVfrUmiVqJRAoGAeNCINoxChvSeVJpd2v9jans9uE8NMdtFilAPDob2PN0U5w8Q2MZnzRTtRM+nr0BfspMh/uwg5OhdlHbDr/QKBnhwF/DpU3hdxXwDcjhdtfy3TO4gUSTbrYdv4cX62R+jIvcWSyCzFxpW/ly7xMMj7NBhdeFcElXfPgHaiPfOAnECgYBwgt6dmS8ZTPyf5bsU4zOWsGNaeqVfz+YOrpvlXP9tvXXFUdkJ8ffc1TeJHJwSx7b9vQZ76vnm9ZDPyCtOnJPaH3trV2fuTHxJfOn5bH6BVafQT9yUIv7RQtXMuBT6frXpHr28gWEtn8/x2PXcwwE4ZYU6taGz3vacibK5vSXt6w==
    ali-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArzOCyNzjrfmmVNjNvLZ8yibcgZZq+9BOyIk1nvDGV96l0WUwnA/9mxtUP62tyFQUuCptq/9MTrFbq5BP4FA8PLcXtNQl4EalmyEA2IbVnQc/du1rGlYYCqiNN3kNa07X05YKeVV1JD1PsGmgdmenZJhVExX62SOmPZ5lbO19BgaH0lgpCleeXJaK+6N9URbW1VVOU30QhVEkYUHlSyDq5ZI4W+lPnoNcOOQmmuknBA4wCH3c/KvGK3U7nxp3iQdlPT0OEvolT4JBsaRhePaKtgMex22NVnK3u8exj6seD8beQnh5bfZYNVDLUIR3IzbAnaQaCMGOgn8hL4y8Xx5MQQIDAQAB
  notify-url: http://81.68.81.2:8001/pay/notify
  return-url: http://81.68.81.2/#/order/list
swagger:
  enabled: true
security:
  header-token-key: token
mybatis:
  mapper-locations: classpath:mapper/*.xml